name: Generate Articles

on:
  push:

permissions:
  contents: write # Add permissions to write to repository

jobs:
  process-topics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for authentication

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install openai python-frontmatter

      - name: Run generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          MODEL_NAME: "your-custom-model"
        run: |
          python scripts/generate_articles.py "topics/*.md"
          python scripts/update_index.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add articles/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate articles"
          git push
