name: Convert Issue to Topic

on:
  issues:
    types: [opened]

jobs:
  create-topic:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create branch
        run: |
          issue_date=$(date +%Y-%m-%d)
          issue_title=$(echo "${{ github.event.issue.title }}" | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')
          branch_name="topic/${issue_date}-${issue_title}"
          git checkout -b $branch_name
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "FILE_NAME=${issue_date}-${issue_title}.md" >> $GITHUB_ENV

      - name: Create topic file
        run: |
          mkdir -p topics
          cat > "topics/$FILE_NAME" << EOL
          ---
          title: "${{ github.event.issue.title }}"
          date: $(date +%Y-%m-%d)
          issue: ${{ github.event.issue.number }}
          ---

          ${{ github.event.issue.body }}
          EOL

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add topics/
          git commit -m "feat: convert issue #${{ github.event.issue.number }} to topic"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "🤖 Convert issue #${{ github.event.issue.number }} to topic"
          body: |
            This PR was automatically created from issue #${{ github.event.issue.number }}.

            Original issue title: ${{ github.event.issue.title }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: automatic
