name: Convert Issue to Topic

on:
  issues:
    types: [opened]

jobs:
  create-topic:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          issue_date=$(date +%Y-%m-%d)
          echo "BRANCH_NAME=topic/issue-${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "FILE_NAME=${issue_date}-issue-${{ github.event.issue.number }}.md" >> $GITHUB_ENV

      - name: Create topic file
        run: |
          mkdir -p topics
          cat > "topics/$FILE_NAME" << EOL
          ---
          title: "${{ github.event.issue.title }}"
          date: $(date +%Y-%m-%d)
          issue: ${{ github.event.issue.number }}
          ---

          ${{ github.event.issue.body }}
          EOL

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: convert issue #${{ github.event.issue.number }} to topic"
          title: "🤖 Convert issue #${{ github.event.issue.number }} to topic"
          body: |
            This PR was automatically created from issue #${{ github.event.issue.number }}.

            Original issue title: ${{ github.event.issue.title }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: automatic
          delete-branch: true
